### ISSUE TITLE
Documentation Inconsistency

### ISSUE THREAD

**Issue by dnwillia** [pyansys/pypim#71]
In the documentation there is this note:

![image](https://user-images.githubusercontent.com/1747766/186767849-dadd9e7e-dbdc-4958-b761-f7fd54ebbc6b.png)

but

- I can look at the implementation on GitHub quite easily, the repository is there.
- I can install the packages from PyPi.  So, it's been distributed.

**Comment by plule-ansys** [comment]
Thank you @dnwillia, I've opened #72 in order to clarify the status
